$(document).ready(function(){
$('.owl-one').owlCarousel({
    loop:true,
    margin:4,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
})

$(document).ready(function(){
    $('.owl-two').owlCarousel({
        loop:true,
        margin:4,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
    })
    })

$(document).ready(function(){
    $('.owl-three').owlCarousel({
        loop:true,
        margin:4,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
    })
    })

$(document).ready(function(){
    $('.owl-four').owlCarousel({
        loop:true,
        margin:4,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
    })
    })

$(document).ready(function(){
    $('.owl-five').owlCarousel({
        loop:true,
        margin:4,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            1000:{
                items:5
            }
        }
    })
    })
